<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <NoWarn>$(NoWarn);CS1591;NU1901;NU1902;NU1903;NU1904;CA1805;CA1822;CA1859;CA1515;CA1861;CA1707;CA1305;CA1850;CA1304;CA1307;CA1311;CA1816;CA1848;CA1873</NoWarn>
  </PropertyGroup>
</Project>
