<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GqlGateway.Domain\GqlGateway.Domain.csproj" />
    <ProjectReference Include="..\..\..\gql_sqlparser\TrinoSqlEngine.csproj" />
  </ItemGroup>



  <ItemGroup>
    <PackageReference Include="Casbin.NET" Version="2.21.3" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="HotChocolate.Language" Version="16.6.7" />
    <PackageReference Include="MemoryPack" Version="1.21.4" />
    <PackageReference Include="Parquet.Net" Version="5.0.2" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
